CREATE DATABASE BANK_ANALYTICS;
GO
USE BANK_ANALYTICS;

SELECT * FROM BANK_TRANSACTION;

--1. TOTAL NUMBER OF TRANSACTIONS, TOTAL DEBIT AMOUNT, TOTAL CREDIT AMOUNT
SELECT
	COUNT(*) AS TOTAL_NUMBER_OF_TRANSACTIONS,
	ROUND(SUM(DEBIT_AMOUNT),2) AS TOTAL_DEBIT_AMOUNT,
	ROUND(SUM(CREDIT_AMOUNT),2) AS TOTAL_CREDIT_AMOUNT
FROM BANK_TRANSACTION;

--2. BRANCH WISE TRANSACTION VOLUME AND TRANSACTION VALUE
SELECT
	BRANCH,
	COUNT(*) AS TRANSACTION_VOLUME,
	(ROUND(SUM(DEBIT_AMOUNT),2) + ROUND(SUM(CREDIT_AMOUNT),2)) AS TRANSACTION_VALUE
FROM BANK_TRANSACTION
GROUP BY BRANCH

--3. AVERAGE TRANSACTION AMOUNT PER TRANSACTION TYPE (DEBIT/ CREDIT)
SELECT
	'DEBIT' AS TRANSACTION_TYPE,
	AVG(DEBIT_AMOUNT) AS AVERAGE_TRANSACTION_AMOUNT
FROM BANK_TRANSACTION
WHERE DEBIT_AMOUNT IS NOT NULL

UNION ALL

SELECT
	'CREDIT' AS TRANSACTION_TYPE,
	AVG(CREDIT_AMOUNT) AS AVERAGE_TRANSACTION_AMOUNT
FROM BANK_TRANSACTION
WHERE CREDIT_AMOUNT IS NOT NULL

--4. MONTH-ON-MONTH GROWTH IN TOTAL_TRANSACTION_AMOUNT

WITH MONTHLY_TRANSACTION AS
(SELECT
	YEAR(TRANSACTION_DATE) AS TXN_YEAR,
	MONTH(TRANSACTION_DATE) AS TXN_MONTH,
	(SUM(ISNULL(CREDIT_AMOUNT,0)) + SUM(ISNULL(DEBIT_AMOUNT,0))) AS TOTAL_TRANSACTION_AMOUNT
FROM BANK_TRANSACTION
GROUP BY YEAR(TRANSACTION_DATE),MONTH(TRANSACTION_DATE)
),
MOM_CALC AS (
	SELECT 
		TXN_YEAR,
		TXN_MONTH,
		TOTAL_TRANSACTION_AMOUNT,
		LAG(TOTAL_TRANSACTION_AMOUNT) OVER(ORDER BY TXN_YEAR,TXN_MONTH) AS PREVIOUS_MONTH_AMOUNT
	FROM MONTHLY_TRANSACTION
)
SELECT
	TXN_YEAR,
	TXN_MONTH,
	TOTAL_TRANSACTION_AMOUNT,
	PREVIOUS_MONTH_AMOUNT,
	CASE
		WHEN PREVIOUS_MONTH_AMOUNT = 0 THEN NULL
		ELSE 
			ROUND(((TOTAL_TRANSACTION_AMOUNT - PREVIOUS_MONTH_AMOUNT)*100 / PREVIOUS_MONTH_AMOUNT),2)
	END AS MOM_GROWTH_PERCENT
FROM MOM_CALC
ORDER BY TXN_YEAR, TXN_MONTH;


--5. WEEKEND VS WEEKDAY TRANSACTION COMPARISION
SET DATEFIRST 1;

WITH DAY_CLASSIFICATION AS (
    SELECT
        CASE
            WHEN DATEPART(WEEKDAY, TRANSACTION_DATE) IN (6,7)
                THEN 'WEEKEND'
            ELSE 'WEEKDAY'
        END AS DAY_TYPE,
        DEBIT_AMOUNT,
        CREDIT_AMOUNT
    FROM BANK_TRANSACTION
)
SELECT
    DAY_TYPE,
    COUNT(*) AS TRANSACTION_VOLUME,
    ROUND(SUM(ISNULL(DEBIT_AMOUNT,0) + ISNULL(CREDIT_AMOUNT,0)),2) AS TRANSACTION_VALUE
FROM DAY_CLASSIFICATION
GROUP BY DAY_TYPE;

--6. IDENTIFY SUSPICIOUS DAYS WHERE DEBIT AMOUNT > CREDIT AMOUNT BY 20%
SELECT
    CAST(TRANSACTION_DATE AS DATE) AS TRANSACTION_DAY,
    SUM(ISNULL(DEBIT_AMOUNT,0)) AS TOTAL_DEBIT,
    SUM(ISNULL(CREDIT_AMOUNT,0)) AS TOTAL_CREDIT,
    CAST(
        (SUM(ISNULL(DEBIT_AMOUNT,0)) - SUM(ISNULL(CREDIT_AMOUNT,0))) * 100.0
        / NULLIF(SUM(ISNULL(CREDIT_AMOUNT,0)),0)
    AS DECIMAL(10,2)) AS DEBIT_EXCESS_PERCENT
FROM BANK_TRANSACTION
GROUP BY CAST(TRANSACTION_DATE AS DATE)
HAVING SUM(ISNULL(DEBIT_AMOUNT,0)) > SUM(ISNULL(CREDIT_AMOUNT,0)) * 1.2;

--7. BRANCH WISE TOP 5 CUSTOMERS BY TRANSACTION AMOUNT
WITH CUSTOMER_BRANCH_TRANSACTION AS (
    SELECT
        BRANCH,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        ROUND(SUM(ISNULL(DEBIT_AMOUNT,0) + ISNULL(CREDIT_AMOUNT,0)),2) AS TOTAL_TRANSACTION_AMOUNT
    FROM BANK_TRANSACTION
    GROUP BY
        BRANCH,
        CUSTOMER_ID,
        CUSTOMER_NAME
),
RANKED_CUSTOMER AS (
    SELECT
        BRANCH,
        CUSTOMER_ID,
        CUSTOMER_NAME,
        TOTAL_TRANSACTION_AMOUNT,
        DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY TOTAL_TRANSACTION_AMOUNT DESC) AS BRANCH_RANK
    FROM CUSTOMER_BRANCH_TRANSACTION
)
SELECT
    BRANCH,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    TOTAL_TRANSACTION_AMOUNT,
    BRANCH_RANK
FROM RANKED_CUSTOMER
WHERE BRANCH_RANK <= 5
ORDER BY BRANCH, BRANCH_RANK;

--8. CUSTOMERS WHO HAVE MULTIPLE ACCOUNTS

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    COUNT(DISTINCT ACCOUNT_NUMBER) AS ACCOUNT_COUNT
FROM BANK_TRANSACTION
GROUP BY
    CUSTOMER_ID,
    CUSTOMER_NAME
HAVING COUNT(DISTINCT ACCOUNT_NUMBER) > 1
ORDER BY ACCOUNT_COUNT DESC;

--9. ACCOUNTS WHOSE TRANSACTION AMOUNT IS ABOVE OVERALL AVERAGE.
SELECT
    ACCOUNT_NUMBER,
    ROUND(SUM(ISNULL(CREDIT_AMOUNT,0) + ISNULL(DEBIT_AMOUNT,0)),2) AS TOTAL_TRANSACTION_AMOUNT
FROM BANK_TRANSACTION
GROUP BY ACCOUNT_NUMBER
HAVING 
    ROUND(SUM(ISNULL(CREDIT_AMOUNT,0) + ISNULL(DEBIT_AMOUNT,0)),2) > 
    (
        SELECT 
            AVG(ACCOUNT_TOTAL)
        FROM (
                SELECT ACCOUNT_NUMBER,
                    SUM(ISNULL(CREDIT_AMOUNT,0) + ISNULL(DEBIT_AMOUNT,0))AS ACCOUNT_TOTAL
                FROM BANK_TRANSACTION
                GROUP BY ACCOUNT_NUMBER) T
     )
ORDER BY TOTAL_TRANSACTION_AMOUNT DESC;
    
--10. CALCULATE RUNNING BALANCE PER ACCOUNT
SELECT
    ACCOUNT_NUMBER,
    TRANSACTION_DATE,
    CREDIT_AMOUNT,
    DEBIT_AMOUNT,
    NET_TRANSACTION_AMOUNT,
    SUM(ISNULL(NET_TRANSACTION_AMOUNT,0))
        OVER (PARTITION BY ACCOUNT_NUMBER ORDER BY TRANSACTION_DATE 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS RUNNING_BALANCE
FROM BANK_TRANSACTION
ORDER BY ACCOUNT_NUMBER, TRANSACTION_DATE;

--11. TOP 3 TRANSACTIONS PER ACCOUNT
SELECT *
FROM (
    SELECT
        ACCOUNT_NUMBER,
        ISNULL(CREDIT_AMOUNT,0)+ ISNULL(DEBIT_AMOUNT,0) AS TRANSACTION_AMOUNT,
        DENSE_RANK() OVER(PARTITION BY ACCOUNT_NUMBER ORDER BY ISNULL(CREDIT_AMOUNT,0)+ ISNULL(DEBIT_AMOUNT,0) DESC) AS RNK
    FROM BANK_TRANSACTION
    ) T
WHERE RNK <= 3

--12. DEBIT TO CREDIT RATIO BY BRANCH
SELECT
    BRANCH,
    ROUND(SUM(ISNULL(DEBIT_AMOUNT, 0)) * 1.0
        / NULLIF(SUM(ISNULL(CREDIT_AMOUNT, 0)), 0),2) AS DEBIT_TO_CREDIT_RATIO
FROM BANK_TRANSACTION
GROUP BY BRANCH;

--13. CREATE A MONTHLY BANKING KPI VIEW

CREATE VIEW VW_MONTHLY_BANKING_KPIS AS
SELECT
    DATENAME(YEAR, TRANSACTION_DATE) + '-' + 
    RIGHT('0' + CAST(MONTH(TRANSACTION_DATE) AS VARCHAR), 2) AS TRANSACTION_MONTH,

    COUNT(*) AS TOTAL_TRANSACTIONS,

    SUM(ISNULL(CREDIT_AMOUNT, 0)) AS TOTAL_CREDIT_AMOUNT,

    SUM(ISNULL(DEBIT_AMOUNT, 0)) AS TOTAL_DEBIT_AMOUNT,

    -- NET TRANSACTION AMOUNT
    SUM(ISNULL(CREDIT_AMOUNT, 0)) - SUM(ISNULL(DEBIT_AMOUNT, 0)) AS NET_TRANSACTION_AMOUNT,

    -- CREDIT TO DEBIT RATIO
    ROUND(
        SUM(ISNULL(CREDIT_AMOUNT, 0)) * 1.0 / NULLIF(SUM(ISNULL(DEBIT_AMOUNT, 0)), 0),
        2
    ) AS CREDIT_TO_DEBIT_RATIO,

    -- DEBIT TO CREDIT RATIO
    ROUND(
        SUM(ISNULL(DEBIT_AMOUNT, 0)) * 1.0
        / NULLIF(SUM(ISNULL(CREDIT_AMOUNT, 0)), 0),
        2
    ) AS DEBIT_TO_CREDIT_RATIO,

    -- AVERAGE ACCOUNT BALANCE
    AVG(ISNULL(BALANCE, 0)) AS AVG_ACCOUNT_BALANCE,

    -- ACCOUNT ACTIVITY RATIO
    ROUND(
        COUNT(*) * 1.0
        / NULLIF(AVG(ISNULL(BALANCE, 0)), 0),
        6
    ) AS ACCOUNT_ACTIVITY_RATIO

FROM BANK_TRANSACTION
GROUP BY
    DATENAME(YEAR, TRANSACTION_DATE),
    MONTH(TRANSACTION_DATE);

--14. CREATE A CUSTOMER 360 VIEW
CREATE VIEW VW_CUSTOMER_360 AS
WITH CUSTOMER_BASE AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        BRANCH,
        BANK_NAME,
        ACCOUNT_NUMBER,
        CREDIT_AMOUNT,
        DEBIT_AMOUNT,
        NET_TRANSACTION_AMOUNT,
        TRANSACTION_DATE,
        HIGH_RISK_TRANSACTION_FLAG
    FROM BANK_TRANSACTION
),
CUSTOMER_AGGREGATES AS (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_NAME,
        BRANCH,
        BANK_NAME,

        COUNT(DISTINCT ACCOUNT_NUMBER) AS TOTAL_ACCOUNTS,
        COUNT(*) AS TOTAL_TRANSACTIONS,

        SUM(ISNULL(CREDIT_AMOUNT,0)) AS TOTAL_CREDIT,
        SUM(ISNULL(DEBIT_AMOUNT,0)) AS TOTAL_DEBIT,
        SUM(ISNULL(NET_TRANSACTION_AMOUNT,0)) AS NET_TRANSACTION_AMOUNT,

        AVG(ISNULL(CREDIT_AMOUNT,0) + ISNULL(DEBIT_AMOUNT,0)) 
            AS AVG_TRANSACTION_AMOUNT,

        COUNT(DISTINCT YEAR(TRANSACTION_DATE) * 100 + MONTH(TRANSACTION_DATE)) AS ACTIVE_MONTHS,

        SUM(CASE 
                WHEN HIGH_RISK_TRANSACTION_FLAG = 1 THEN 1 
                ELSE 0 
            END) AS HIGH_RISK_TXN_COUNT

    FROM CUSTOMER_BASE
    GROUP BY
        CUSTOMER_ID,
        CUSTOMER_NAME,
        BRANCH,
        BANK_NAME
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    BRANCH,
    BANK_NAME,
    TOTAL_ACCOUNTS,
    TOTAL_TRANSACTIONS,
    ACTIVE_MONTHS,

    CAST(TOTAL_CREDIT AS DECIMAL(18,2)) AS TOTAL_CREDIT,
    CAST(TOTAL_DEBIT AS DECIMAL(18,2)) AS TOTAL_DEBIT,
    CAST(NET_TRANSACTION_AMOUNT AS DECIMAL(18,2)) AS NET_TRANSACTION_AMOUNT,
    CAST(AVG_TRANSACTION_AMOUNT AS DECIMAL(18,2)) AS AVG_TRANSACTION_AMOUNT,

    HIGH_RISK_TXN_COUNT,
    CASE
        WHEN HIGH_RISK_TXN_COUNT > 0 THEN 'YES'
        ELSE 'NO'
    END AS HIGH_RISK_CUSTOMER_FLAG

FROM CUSTOMER_AGGREGATES;
